persistentVolume:
  name: my-pv2
  size: 10Gi
  accessMode: ReadWriteOnce
  reclaimPolicy: Retain
  storageClassName: standard
  hostPath: /mnt/data/my-pv

persistentVolumeClaim:
  name: my-pvc2
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClassName: standard

statefulSet:
  name: my-statefulset
  replicas: 4
  appLabel: my-app
  initContainerImage: busybox
  containerImage: nginx:latest
  storageRequest: 1Gi
  storageClassName: standard

